<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sourabhdh-w7" name="Tests [LoginNormalUser]" tests="1" failures="1" timestamp="10 Nov 2016 10:55:09 GMT" time="43.958" errors="0">
  <testcase name="createNewIdea" time="3.859" classname="com.test.PublicUser">
    <failure type="java.lang.AssertionError" message="expected [https://ucsdtest.ideator.com/] but found [https://ucsdtest.ideator.com/ideas?after_login=true]">
      <![CDATA[java.lang.AssertionError: expected [https://ucsdtest.ideator.com/] but found [https://ucsdtest.ideator.com/ideas?after_login=true]
	at com.test.PublicUser.createNewIdea(PublicUser.java:60)
	at com.test.IdeatorStart.testNgRun(IdeatorStart.java:53)
	at com.test.IdeatorStart.main(IdeatorStart.java:118)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- createNewIdea -->
</testsuite> <!-- Tests [LoginNormalUser] -->
