<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sourabhdh-w7" name="Tests com.test.AdminTest" tests="1" failures="1" timestamp="18 Oct 2016 05:43:38 GMT" time="177.601" errors="0">
  <testcase name="Login" time="30.204" classname="com.test.AdminTest">
    <failure type="java.lang.AssertionError" message="expected [https://ucsdtest.ideator.com/sign_in] but found [https://ucsdtest.ideator.com/ideas?after_login=true]">
      <![CDATA[java.lang.AssertionError: expected [https://ucsdtest.ideator.com/sign_in] but found [https://ucsdtest.ideator.com/ideas?after_login=true]
	at com.test.AdminTest.Login(Unknown Source)
	at com.test.IdeatorStart.testNgRun(IdeatorStart.java:52)
	at com.test.IdeatorStart.main(IdeatorStart.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
</testsuite> <!-- Tests com.test.AdminTest -->
